### ISSUE TITLE
__version_str___

### ISSUE THREAD

**Issue by sibero80** [SeraphicCorp/docker-google-assistant#1]
Hello there,

While running for the fist time on a Raspberry Pi 2, I'm getting this error:

```
Traceback (most recent call last):
  File "/env/bin/googlesamples-assistant-hotword", line 11, in <module>
    sys.exit(main())
  File "/env/lib/python3.4/site-packages/googlesamples/assistant/library/hotword.py", line 129, in main
    Assistant.__version_str__())
AttributeError: type object 'Assistant' has no attribute '__version_str__'
```

Any clue what it might be?

Thank you!

**Comment by SeraphicRav** [comment]
Hi !

Sorry for the late reply. I could get my hand on a Raspberry Pi 3 and I get no error with either the image on Docker hub or building the docker image from scratch today.

How did you get this error ? By building the image yourself ?
